[build]
  publish = "."
  command = ""
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[functions]
  node_bundler = "esbuild"

[functions."dart"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/dart-proxy/*"
  to = "https://opendart.fss.or.kr/api/:splat"
  status = 200
  force = true
